version: '3'

services:
  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/srv/jekyll"
    ports:
      - "4000:4000"
    networks:
      - website-network
    entrypoint: tail -f /dev/null
    environment:
      EXECJS_RUNTIME: Disabled

networks:
  website-network:
    driver: bridge
      